import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DatabaseConfig } from '../config/configuration';
import {
  AiAgent,
  AiRequest,
  AiTask,
  AiTemplate,
  AiUsage,
  AuditLog,
  Branch,
  BranchCustomerMixDaily,
  BranchTrafficDaily,
  Campaign,
  Category,
  ChannelConfig,
  ChatMessage,
  ChatThread,
  ContentAsset,
  ContentItem,
  ContentPublishJob,
  Conversation,
  ErpCampaignCache,
  ErpProductCache,
  ErpSalesDaily,
  ErpSalesSummary,
  GoogleReview,
  InboxMessage,
  ListeningKeyword,
  Notification,
  PasswordReset,
  PosImportRun,
  PosSalesLine,
  PosmProject,
  Product,
  ProductPromotionSnapshot,
  ProductSyncRun,
  Promotion,
  RefreshToken,
  Role,
  SalesRecord,
  SalesTarget,
  SignAiResult,
  SignDraft,
  SignExport,
  SignRequest,
  SignRequestAsset,
  SignReview,
  SignTemplate,
  SocialMention,
  SystemSetting,
  Tenant,
  User,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (config: ConfigService) => {
        const db = config.getOrThrow<DatabaseConfig>('database');
        return {
          type: 'mysql',
          host: db.host,
          port: db.port,
          username: db.username,
          password: db.password,
          database: db.database,
          charset: 'utf8mb4_unicode_ci',
          timezone: 'Z',
          entities: [
            Tenant,
            User,
            Role,
            RefreshToken,
            PasswordReset,
            AiTemplate,
            AiRequest,
            AiUsage,
            ContentItem,
            ContentAsset,
            ContentPublishJob,
            Category,
            Product,
            ProductPromotionSnapshot,
            ProductSyncRun,
            Campaign,
            Promotion,
            Notification,
            ChatThread,
            ChatMessage,
            SalesRecord,
            SignAiResult,
            SignDraft,
            SignExport,
            SignRequest,
            SignRequestAsset,
            SignReview,
            SignTemplate,
            Branch,
            AuditLog,
            ErpCampaignCache,
            ErpProductCache,
            ErpSalesDaily,
            ErpSalesSummary,
            PosmProject,
            PosImportRun,
            GoogleReview,
            SocialMention,
            ListeningKeyword,
            AiAgent,
            AiTask,
            ChannelConfig,
            Conversation,
            InboxMessage,
            SystemSetting,
            SalesTarget,
            BranchTrafficDaily,
            BranchCustomerMixDaily,
            PosSalesLine,
          ],
          synchronize: db.synchronize,
          logging: db.logging,
          extra: { connectionLimit: db.connectionLimit },
        };
      },
    }),
  ],
})
export class DatabaseModule {}
