CREATE TABLE IF NOT EXISTS pos_import_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  year_month CHAR(7) NOT NULL,
  drive_file_id VARCHAR(255) NULL,
  filename VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'running',
  total_rows INT UNSIGNED NOT NULL DEFAULT 0,
  imported_rows INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_rows INT UNSIGNED NOT NULL DEFAULT 0,
  receipt_count INT UNSIGNED NOT NULL DEFAULT 0,
  branch_count INT UNSIGNED NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  imported_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pos_import_run_tenant_month (tenant_id, year_month),
  KEY idx_pos_import_run_file (drive_file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_sales_lines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  year_month CHAR(7) NOT NULL,
  import_run_id BIGINT UNSIGNED NULL,
  line_index INT UNSIGNED NOT NULL,
  product_name VARCHAR(500) NULL,
  sku VARCHAR(80) NULL,
  receipt_no VARCHAR(80) NOT NULL,
  sale_date DATE NOT NULL,
  sale_datetime DATETIME NULL,
  branch_code VARCHAR(50) NOT NULL,
  qty DECIMAL(12,3) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  line_amount_before_vat DECIMAL(14,2) NOT NULL DEFAULT 0,
  vat_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  line_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  discount DECIMAL(14,2) NOT NULL DEFAULT 0,
  approved_discount DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_amount_before_vat DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(80) NULL,
  nationality VARCHAR(80) NULL,
  ar_name VARCHAR(255) NULL,
  promotion_name VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_pos_sales_line (tenant_id, year_month, receipt_no, sku, sale_datetime, line_index),
  KEY idx_pos_sales_tenant_month_branch (tenant_id, year_month, branch_code),
  KEY idx_pos_sales_receipt (tenant_id, receipt_no),
  KEY idx_pos_sales_date (tenant_id, sale_date),
  KEY idx_pos_sales_sku (tenant_id, sku),
  KEY idx_pos_sales_nationality (tenant_id, year_month, nationality),
  KEY idx_pos_sales_import_run (import_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
